# Generated by Django 4.2.5 on 2023-10-11 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sketchs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sketch',
            name='test',
        ),
    ]
