# Generated by Django 4.2.5 on 2023-10-02 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sketchs', '0002_sketch_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='sketch',
            name='slug',
            field=models.SlugField(default='', max_length=255),
        ),
    ]
