# Generated by Django 4.2.5 on 2023-10-08 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sketchs', '0005_remove_sketch_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='sketch',
            name='image',
            field=models.ImageField(default='', upload_to='images/'),
        ),
    ]
