# Generated by Django 4.2.5 on 2023-10-08 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sketchs', '0006_sketch_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sketch',
            name='image',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
